// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoEmpresa.Models;

namespace ProjetoEmpresa.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20201215111203_Projeto")]
    partial class Projeto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjetoEmpresa.Models.Empresa", b =>
                {
                    b.Property<int>("empresaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cnpj");

                    b.Property<string>("nomeFantasia")
                        .IsRequired();

                    b.Property<string>("uf")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.HasKey("empresaId");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("ProjetoEmpresa.Models.Fornecedor", b =>
                {
                    b.Property<int>("idfornecedor")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cpf_cnpj")
                        .IsRequired();

                    b.Property<DateTime>("datahora");

                    b.Property<int>("empresaId");

                    b.Property<int>("nascimento");

                    b.Property<string>("nome")
                        .IsRequired();

                    b.Property<string>("pessoa")
                        .IsRequired();

                    b.Property<string>("rg");

                    b.Property<string>("telefone")
                        .IsRequired();

                    b.HasKey("idfornecedor");

                    b.HasIndex("empresaId");

                    b.ToTable("Fornecedores");
                });

            modelBuilder.Entity("ProjetoEmpresa.Models.Fornecedor", b =>
                {
                    b.HasOne("ProjetoEmpresa.Models.Empresa", "Empresa")
                        .WithMany("Fornecedores")
                        .HasForeignKey("empresaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
